### ISSUE TITLE
Error with Docker lambdas

### ISSUE THREAD

**Issue by JanLikar** [kevinrambaud/serverless-functions-base-path#204]
When using this plugin a Docker lambda fails to create because it has no `handler` set.

Would you want me to create a PR?

**Comment by kevinrambaud** [comment]
Yes, sure. If you could also join a reproductible test case to make it easier to check your changes that would be perfect.

**Comment by kevinrambaud** [comment]
I just published version 1.0.33 with your fix. Thanks for your contribution.

**Comment by JanLikar** [comment]
Happy to help!
