### ISSUE TITLE
Move base path check into hook

### ISSUE THREAD

**Issue by chris-feist** [kevinrambaud/serverless-functions-base-path#51]
> Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

https://serverless.com/framework/docs/providers/aws/guide/plugins#serverless-instance

**Comment by kevinrambaud** [comment]
Closing this issue, the update of the functions' path is already done within a method attached to different hooks.
